<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    /** CONSTANTES DE TIERRA  */
     const TIERRA_CATEGORIAS = [
        'fija',
        'movil'
    ];


     const TIERRA_SUBCATEGORIAS = [
         'fija'=>[
            'bardas',
            'buzones',
            'caja de luz',
            'carteles',
            'espectaculares',
            'espectaculares de pantallas digitales',
            'kioscos',
            'lonas',
            'mantas (igual o mayor a 12mts)',
            'mantas (menores a 12 mts)',
            'marquesinas',
            'muebles urbanos',
            'pantallas fijas',
            'parabuses',
            'pendones',
            'propaganda en columnas',
            'puente',
            'valla digital',
            'volantes'
        ],
        'movil'=>[
            'bicicletas,bicitaxis,mototaxis',
            'brigadas',
            'metro',
            'perifoneo',
            'transporte publico',
            'vehiculos particulares',
            'vehiculos publicitarios',
        ]
    ];


    const TIERRA_FIELDS = [
        'fija'=>[
            'bardas'=>[
                'cantidad'=>'integer',
                'alto'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'buzon'=>[
                'cantidad'=>'integer',
                'alto'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'caja de luz'=>[
                'cantidad'=>'integer',
                'alto'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'carteles'=>[
                'cantidad'=>'integer',
                'alto'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'espectaculares'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'espectaculares de pantallas digitales'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'kioscos'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'lonas'=>[
                'cantidad'=>'integer',
                'alto'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'mantas (igual o mayor a 12mts)'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'mantas (menores a 12 mts)'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'marquesinas'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'muebles urbanos'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'pantallas fijas'=>[
                'cantidad'=>'integer',
                'pulgadas'=>'integer',
                'ubicacion'=> 'string',
                'publicidad compartida' => 'string'
            ],
            'parabuses'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'pendones'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'propaganda en columnas'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'puentes'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'tipo publicidad'=>'string',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'valla digital'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida' => 'string'
            ],
            'volantes'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida' => 'string'
            ]
        ],
        'movil'=>[
            'bicicletas,bicitaxis,mototaxis'=>[
                'cantidad'=>'integer',
                'ancho'=>'string',
                'largo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'brigadas'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'metro'=>[
                'cantidad'=>'integer',
                'ancho'=>'string',
                'largo'=>'string',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'perifoneo'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'transporte publico'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'tipo vehiculo'=>'string',
                'placas'=>'string',
                'publicidad compartida'=>'string'
            ],
            'vehiculos particulares'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'vehiculos publicitarios'=>[
                'cantidad'=>'integer',
                'ancho'=>'string',
                'largo'=>'string',
                'placas'=>'string',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
        ]
    ];

    /** CONSTANTES DE EVENTOS  */
    const EVENTO_CATEGORIES = [
        'animacion',
        'espectacular',
        'estructura',
        'produccion',
        'transporte',
        'utilitario'
    ];
    const EVENTO_SUBCATEGORIES = [
        'animacion'=>[
            'animacion',
            'edecanes',
            'grupos musicales / djs',
            'otros'
        ],
        'espectacular'=>[
            'inflable',
            'lonas',
            'otros',
            'pendones',
        ],
        'estructura'=>[
            'banner',
            'baños publicos',
            'carpas',
            'escenario',
            'gradas',
            'mampara',
            'mesas',
            'otros',
            'sillas',
            'sillones',
            'templete',
            'vallas',
        ],
        'produccion'=>[
            'camaras de video',
            'computadoras',
            'consola de audio',
            'drone',
            'equipo de audio',
            'estructura del partido',
            'gruas de camara',
            'luces',
            'microfonos',
            'muro de video (mas de 2 pantallas)',
            'otros',
            'pantallas',
            'personal de seguridad',
            'plantas de luz',
            'proyectores',
            'servicio medico'
        ],
        'transporte'=>[
            'automoviles',
            'camiones',
            'camionetas',
            'combi/microbus',
            'otros',
            'taxi'
        ],
        'utilitario'=>[
            'abanicos',
            'aguas',
            'banderas',
            'bolsas',
            'botones',
            'camisas',
            'chaleco',
            'chamarras',
            'cobija',
            'gorras',
            'impermeable',
            'lonches',
            'mandiles',
            'mangas',
            'mantas (igual o mayor a 12 mts)',
            'mantas (menores a 12 mts)',
            'microperforados',
            'otros',
            'paliacates',
            'playeras',
            'pulseras',
            'refrescos',
            'sombrillas',
            'stickers',
            'sudadera',
            'tortilleros',
            'vasos',
            'vinilonas',
            'volantes'
        ]
    ];


    const EVENTO_FIELDS = [
        'animacion'=>[
            'animacion'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'edecanes'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'grupos musicales / djs'=>[
                'cantidad'=>'integer',
                'cantidad integrantes'=>'integer',
                'nombre'=>'string',
                'publicidad compartida'=>'string'
            ],
            'otros'=>[
                'cantidad'=>'integer',
                'descripcion'=>'string',
                'publicidad compartida'=>'string'
            ]
        ],
        'espectacular'=>[
            'inflable'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'lonas'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'otros'=>[
                'cantidad'=>'integer',
                'descripcion'=>'string',
                'publicidad compartida'=>'string'
            ],
            'pendones'=>[
                'cantidad'=>'integer',
                'largo'=>'integer',
                'ancho'=>'integer',
                'publicidad compartida'=>'string'
            ],
        ],
        'estructura'=>[
            'banner'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'
            ],
            'baños publicos' =>[
                'cantidad'=>'integer',
            ],
            'carpas' =>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'escenario'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'alto'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'gradas'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'alto'=>'integer',
                'cupo'=>'integer',
            ],
            'mampara'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'mesas'=>[
                'cantidad'=>'integer',
                'cupo'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'otros'=>[
                'cantidad'=>'integer',
                'descripcion'=>'string',
                'publicidad compartida'=>'string'
            ],
            'sillas'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'sillones'=>[
                'cantidad'=>'integer',
                'cupo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'templete'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'alto'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'vallas'=>[
                'cantidad'=>'integer',
            ]
        ],
        'produccion'=>[
            'camaras de video'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'computadoras'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'consola de audio'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'drone'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'equipo de audio'=>[
                'numero de bocinas'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'estructura del partido'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'grua de camara'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'luces'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'microfonos'=>[
                'cantidad'=>'integer',
                'inalambrico'=>'string',
                'publicidad compartida'=>'string'
            ],
            'muro de video (mas de 2 pantallas)'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'otros'=>[
                'cantidad'=>'integer',
                'descripcion'=>'string',
                'publicidad compartida'=>'string'
            ],
            'pantallas'=>[
                'cantidad'=>'integer',
                'pulgadas'=>'string',
                'publicidad compartida'=>'string'
            ],
            'personal de seguridad'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'plantas de luz'=>[
                'cantidad'=>'integer',
                'capacidad'=>'string',
                'publicidad compartida'=>'string'
            ],
            'proyectores'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'servicio medico'=>[
                'cantidad'=>'integer',
                'ambulancia'=>'string',
                'publicidad compartida'=>'string'
            ]
        ],
        'transporte'=>[
            'automoviles'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'matricula'=>'string',
                'publicidad compartida'=>'string'
            ],
            'camiones' =>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'matricula'=>'string',
                'publicidad compartida'=>'string'
            ],
            'camionetas'=>[
                'cantidad'=>'integer',
                'publicidad'=>'string',
                'placa'=>'string',
                'publicidad compartida'=>'string'
            ],
            'combi/microbus'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'placa'=>'string',
                'publicidad compartida'=>'string'
            ],
            'otros'=>[
                'cantidad'=>'integer',
                'descripcion'=>'string',
                'placas'=>'string',
                'publicidad compartida'=>'string'
            ],
            'taxi'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'placa'=>'string',
                'publicidad compartida'=>'string'
            ]
        ],
        'utilitario'=>[
            'abanicos'=>[
                'cantidad'=>'integer',
                'publicidad compartida'
            ],
            'aguas'=>[
                'cantidad'=>'integer',
                'capacidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'banderas'=>[
                'cantidad'=>'integer',
                'tamaño'=>'string',
                'publicidad compartida'=>'string'
            ],
            'bolsas'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'botones'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'camisas'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'chaleco'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'chamarras'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'cobija'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'gorras'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'impermeable'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'lonches'=>[
                'cantidad'=>'integer',
                'tipo'=>'string'
            ],
            'mandiles'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'mangas'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'mantas (igual o mayor a 12 mts)'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'mantas (menores a 12 mts)'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'microperforados'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'otros'=>[
                'cantidad'=>'integer',
                'descripcion'=>'string',
                'publicidad compartida'=>'string'
            ],
            'paliacates'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'playeras'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'pulseras'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'refrescos'=>[
                'cantidad'=>'integer',
                'capacidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'sombrillas'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'stickers'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'sudadera'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'tortilleros'=>[
                'cantidad'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'vasos'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ],
            'vinilonas'=>[
                'cantidad'=>'integer',
                'ancho'=>'integer',
                'largo'=>'integer',
                'publicidad compartida'=>'string'
            ],
            'volantes'=>[
                'cantidad'=>'integer',
                'tipo'=>'string',
                'publicidad compartida'=>'string'
            ]
        ]
    ];


     const MUNICIPIOS = [
         'AGUASCALIENTES' => [
             'AGUASCALIENTES',
             'ASIENTOS',
             'CALVILLO',
             'COSIO',
             'EL LLANO',
             'JESUS MARIA',
             'PABELLON DE ARTEAGA',
             'RINCON DE ROMOS',
             'SAN FRANCISCO DE LOS ROMO',
             'SAN JOSE DE GRACIA',
             'TEPEZALA'
         ],
         'BAJA CALIFORNIA' => [
             'ENSENADA',
             'MEXICALI',
             'PLAYAS DE ROSARITO',
             'TECATE',
             'TIJUANA'
         ],
         'BAJA CALIFORNIA SUR' => [
             'COMONDU',
             'LA PAZ',
             'LORETO',
             'LOS CABOS',
             'MULEGE'
         ],
         'CAMPECHE' => [
             'CALAKMUL',
             'CALKINI',
             'CAMPECHE',
             'CANDELARIA',
             'CARMEN',
             'CHAMPOTON',
             'ESCARCEGA',
             'HECELCHAKAN',
             'HOPELCHEN',
             'PALIZADA',
             'TENABO'
         ],
         'COAHUILA' => [
             'ABASOLO',
             'ACUÑA',
             'ALLENDE',
             'ARTEAGA',
             'CANDELA',
             'CASTAÑOS',
             'CUATROCIENEGAS',
             'ESCOBEDO',
             'FRANCISCO I. MADERO',
             'FRONTERA',
             'GENERAL CEPEDA',
             'GUERRERO',
             'HIDALGO',
             'JIMENEZ',
             'JUAREZ',
             'LAMADRID',
             'MATAMOROS',
             'MONCLOVA',
             'MORELOS',
             'MUZQUIZ',
             'NADADORES',
             'NAVA',
             'OCAMPO',
             'PARRAS',
             'PIEDRAS NEGRAS',
             'PROGRESO',
             'RAMOS ARIZPE',
             'SABINAS',
             'SACRAMENTO',
             'SALTILLO',
             'SAN BUENAVENTURA',
             'SAN JUAN DE SABINAS',
             'SAN PEDRO',
             'SIERRA MOJADA',
             'TORREON',
             'VIESCA',
             'VILLA UNION',
             'ZARAGOZA'
         ],
         'COLIMA' => [
             'COLIMA0',
             'COMALA0',
             'COQUIMATLAN0',
             'CUAUHTEMOC0',
             'VILLA DE ALVAREZ0',
             'ARMERIA0',
             'IXTLAHUACAN0',
             'MANZANILLO0',
             'MINATITLAN0',
             'TECOMAN0'
         ],
         'CHIAPAS' => [
             'ACACOYAGUA',
             'ACALA',
             'ACAPETAHUA',
             'ALDAMA',
             'ALTAMIRANO',
             'AMATAN',
             'AMATENANGO DE LA FRONTERA',
             'AMATENANGO DEL VALLE',
             'ANGEL ALBINO CORZO',
             'ARRIAGA',
             'BEJUCAL DE OCAMPO',
             'BELLA VISTA',
             'BENEMERITO DE LAS AMERICAS',
             'BERRIOZABAL',
             'BOCHIL',
             'CACAHOATAN',
             'CATAZAJA',
             'CHALCHIHUITAN',
             'CHAMULA',
             'CHANAL',
             'CHAPULTENANGO',
             'CHENALHO',
             'CHIAPA DE CORZO',
             'CHIAPILLA',
             'CHICOASEN',
             'CHICOMUSELO',
             'CHILON',
             'CINTALAPA',
             'COAPILLA',
             'COMITAN DE DOMINGUEZ',
             'COPAINALA',
             'EL BOSQUE',
             'EL PORVENIR',
             'ESCUINTLA',
             'FRANCISCO LEON',
             'FRONTERA COMALAPA',
             'FRONTERA HIDALGO',
             'HUEHUETAN',
             'HUITIUPAN',
             'HUIXTAN',
             'HUIXTLA',
             'IXHUATAN',
             'IXTACOMITAN',
             'IXTAPA',
             'IXTAPANGAJOYA',
             'JIQUIPILAS',
             'JITOTOL',
             'LA CONCORDIA',
             'LA GRANDEZA',
             'LA INDEPENDENCIA',
             'LA LIBERTAD',
             'LA TRINITARIA',
             'LARRAINZAR',
             'LAS MARGARITAS',
             'LAS ROSAS',
             'MAPASTEPEC',
             'MARAVILLA TENEJAPA',
             'MARQUES DE COMILLAS',
             'MAZAPA DE MADERO',
             'MAZATAN',
             'METAPA',
             'MITONTIC',
             'MONTECRISTO DE GUERRERO',
             'MOTOZINTLA',
             'NICOLAS RUIZ',
             'OCOSINGO',
             'OCOTEPEC',
             'OCOZOCOAUTLA DE ESPINOSA',
             'OSTUACAN',
             'OSUMACINTA',
             'OXCHUC',
             'PALENQUE',
             'PANTELHO',
             'PANTEPEC',
             'PICHUCALCO',
             'PIJIJIAPAN',
             'PUEBLO NUEVO SOLISTAHUACAN',
             'RAYON',
             'REFORMA',
             'SABANILLA',
             'SALTO DE AGUA',
             'SAN ANDRES DURAZNAL',
             'SAN CRISTOBAL DE LAS CASAS',
             'SAN FERNANDO',
             'SAN JUAN CANCUC',
             'SAN LUCAS',
             'SANTIAGO EL PINAR',
             'SILTEPEC',
             'SIMOJOVEL',
             'SITALA',
             'SOCOLTENANGO',
             'SOLOSUCHIAPA',
             'SOYALO',
             'SUCHIAPA',
             'SUCHIATE',
             'SUNUAPA',
             'TAPACHULA',
             'TAPALAPA',
             'TAPILULA',
             'TECPATAN',
             'TENEJAPA',
             'TEOPISCA',
             'TILA',
             'TONALA',
             'TOTOLAPA',
             'TUMBALA',
             'TUXTLA CHICO',
             'TUXTLA GUTIERREZ',
             'TUZANTAN',
             'TZIMOL',
             'UNION JUAREZ',
             'VENUSTIANO CARRANZA',
             'VILLA CORZO',
             'VILLACOMALTITLAN',
             'VILLAFLORES',
             'YAJALON',
             'ZINACANTAN'
         ],
         'CHIHUAHUA' => [
             'AHUMADA',
             'AQUILES SERDAN',
             'ASCENSION',
             'BACHINIVA',
             'BALLEZA',
             'BATOPILAS',
             'BOCOYNA',
             'BUENAVENTURA',
             'CAMARGO',
             'CARICHI',
             'CASAS GRANDES',
             'CHIHUAHUA',
             'CHINIPAS',
             'CORONADO',
             'COYAME DEL SOTOL',
             'CUSIHUIRIACHI',
             'DELICIAS',
             'DR. BELISARIO DOMINGUEZ',
             'EL TULE',
             'GALEANA',
             'GOMEZ FARIAS',
             'GRAN MORELOS',
             'GUACHOCHI',
             'GUADALUPE',
             'GUADALUPE Y CALVO',
             'GUAZAPARES',
             'HIDALGO DEL PARRAL',
             'HUEJOTITAN',
             'IGNACIO ZARAGOZA',
             'JANOS',
             'JULIMES',
             'LA CRUZ',
             'LOPEZ',
             'MADERA',
             'MAGUARICHI',
             'MANUEL BENAVIDES',
             'MATACHI',
             'MEOQUI',
             'MORIS',
             'NAMIQUIPA',
             'NONOAVA',
             'NUEVO CASAS GRANDES',
             'OJINAGA',
             'PRAXEDIS G. GUERRERO',
             'RIVA PALACIO',
             'ROSALES',
             'ROSARIO',
             'SAN FRANCISCO DE BORJA',
             'SAN FRANCISCO DE CONCHOS',
             'SAN FRANCISCO DEL ORO',
             'SANTA BARBARA',
             'SANTA ISABEL',
             'SATEVO',
             'SAUCILLO',
             'TEMOSACHIC',
             'URIQUE',
             'URUACHI',
             'VALLE DE ZARAGOZA'
         ],
         'CIUDAD DE MEXICO' => [
             'ALVARO OBREGON',
             'AZCAPOTZALCO',
             'BENITO JUAREZ',
             'COYOACAN',
             'CUAJIMALPA DE MORELOS',
             'CUAUTHEMOC',
             'GUSTAVO A. MADERO',
             'IZTACALCO',
             'IZTAPALAPA',
             'LA MAGDALENA CONTRERAS',
             'MIGUEL HIDALGO',
             'MILPA ALTA',
             'TLAHUAC',
             'TLALPAN',
             'VENUSTIANO CARRANZA',
             'XOCHIMILCO'
         ],
         'DURANGO' => [
             'CANATLAN',
             'CANELAS',
             'CONETO DE COMONFORT',
             'CUENCAME',
             'DURANGO',
             'EL ORO',
             'GOMEZ PALACIO',
             'GUADALUPE VICTORIA',
             'GUANACEVI',
             'INDE',
             'LERDO',
             'MAPIMI',
             'MEZQUITAL',
             'NAZAS',
             'NOMBRE DE DIOS',
             'NUEVO IDEAL',
             'OTAEZ',
             'PANUCO DE CORONADO',
             'PEÑON BLANCO',
             'POANAS',
             'PUEBLO NUEVO',
             'RODEO',
             'SAN BERNARDO',
             'SAN DIMAS',
             'SAN JUAN DE GUADALUPE',
             'SAN JUAN DEL RIO',
             'SAN LUIS DEL CORDERO',
             'SAN PEDRO DEL GALLO',
             'SANTA CLARA',
             'SANTIAGO PAPASQUIARO',
             'SIMON BOLIVAR',
             'SUCHIL',
             'TAMAZULA',
             'TEPEHUANES',
             'TLAHUALILO',
             'TOPIA',
             'VICENTE GUERRERO'
         ],
         'GUANAJUATO' => [
             'ACAMBARO',
             'APASEO EL ALTO',
             'APASEO EL GRANDE',
             'ATARJEA',
             'CELAYA',
             'COMONFORT',
             'CORONEO',
             'CORTAZAR',
             'CUERAMARO',
             'DOCTOR MORA',
             'DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL',
             'GUANAJUATO',
             'HUANIMARO',
             'IRAPUATO',
             'JARAL DEL PROGRESO',
             'JERECUARO',
             'LEON',
             'MANUEL DOBLADO',
             'MOROLEON',
             'PENJAMO',
             'PURISIMA DEL RINCON',
             'ROMITA',
             'SALAMANCA',
             'SALVATIERRA',
             'SAN DIEGO DE LA UNION',
             'SAN FELIPE',
             'SAN FRANCISCO DEL RINCON',
             'SAN JOSE ITURBIDE',
             'SAN LUIS DE LA PAZ',
             'SAN MIGUEL DE ALLENDE',
             'SANTA CATARINA',
             'SANTA CRUZ DE JUVENTINO ROSAS',
             'SANTIAGO MARAVATIO',
             'SILAO DE LA VICTORIA',
             'TARANDACUAO',
             'TARIMORO',
             'TIERRA BLANCA',
             'URIANGATO',
             'VALLE DE SANTIAGO',
             'VICTORIA',
             'VILLAGRAN',
             'XICHU',
             'YURIRIA'
         ],
         'GUERRERO' => [
             'ACAPULCO DE JUAREZ',
             'ACATEPEC',
             'AHUACUOTZINGO',
             'AJUCHITLAN DEL PROGRESO',
             'ALCOZAUCA DE GUERRERO',
             'ALPOYECA',
             'APAXTLA',
             'ARCELIA',
             'ATENANGO DEL RIO',
             'ATLAMAJALCINGO DEL MONTE',
             'ATLIXTAC',
             'ATOYAC DE ALVAREZ',
             'AYUTLA DE LOS LIBRES',
             'AZOYU',
             'BUENAVISTA DE CUELLAR',
             'CHILAPA DE ALVAREZ',
             'CHILPANCINGO DE LOS BRAVO',
             'COAHUAYUTLA DE JOSE MARIA IZAZAGA',
             'COCHOAPA EL GRANDE',
             'COCULA',
             'COPALA',
             'COPALILLO',
             'COPANATOYAC',
             'COYUCA DE BENITEZ',
             'COYUCA DE CATALAN',
             'CUAJINICUILAPA',
             'CUALAC',
             'CUAUTEPEC',
             'CUETZALA DEL PROGRESO',
             'CUTZAMALA DE PINZON',
             'EDUARDO NERI',
             'EMILIANO ZAPATA',
             'FLORENCIO VILLARREAL',
             'GENERAL CANUTO A. NERI',
             'GENERAL HELIODORO CASTILLO',
             'HUAMUXTITLAN',
             'HUITZUCO DE LOS FIGUEROA',
             'IGUALA DE LA INDEPENDENCIA',
             'IGUALAPA',
             'ILIATENCO',
             'IXCATEOPAN DE CUAUHTEMOC',
             'JOSE JOAQUIN DE HERRERA',
             'JUAN R. ESCUDERO',
             'JUCHITAN',
             'LA UNION DE ISIDORO MONTES DE OCA',
             'LEONARDO BRAVO',
             'MALINALTEPEC',
             'MARQUELIA',
             'MARTIR DE CUILAPAN',
             'METLATONOC',
             'MOCHITLAN',
             'OLINALA',
             'OMETEPEC',
             'PEDRO ASCENCIO ALQUISIRAS',
             'PETATLAN',
             'PILCAYA',
             'PUNGARABATO',
             'QUECHULTENANGO',
             'SAN LUIS ACATLAN',
             'SAN MARCOS',
             'SAN MIGUEL TOTOLAPAN',
             'TAXCO DE ALARCON',
             'TECOANAPA',
             'TECPAN DE GALEANA',
             'TELOLOAPAN',
             'TEPECOACUILCO DE TRUJANO',
             'TETIPAC',
             'TIXTLA DE GUERRERO',
             'TLACOACHISTLAHUACA',
             'TLACOAPA',
             'TLALCHAPA',
             'TLALIXTAQUILLA DE MALDONADO',
             'TLAPA DE COMONFORT',
             'TLAPEHUALA',
             'XALPATLAHUAC',
             'XOCHIHUEHUETLAN',
             'XOCHISTLAHUACA',
             'ZAPOTITLAN TABLAS',
             'ZIHUATANEJO DE AZUETA',
             'ZIRANDARO',
             'ZITLALA'
             ],
         'HIDALGO' => [
             'ACATLAN',
             'ACAXOCHITLAN',
             'ACTOPAN',
             'AGUA BLANCA DE ITURBIDE',
             'AJACUBA',
             'ALFAJAYUCAN',
             'ALMOLOYA',
             'APAN',
             'ATITALAQUIA',
             'ATLAPEXCO',
             'ATOTONILCO DE TULA',
             'ATOTONILCO EL GRANDE',
             'CALNALI',
             'CARDONAL',
             'CHAPANTONGO',
             'CHAPULHUACAN',
             'CHILCUAUTLA',
             'CUAUTEPEC DE HINOJOSA',
             'EL ARENAL',
             'ELOXOCHITLAN',
             'EMILIANO ZAPATA',
             'EPAZOYUCAN',
             'HUASCA DE OCAMPO',
             'HUAUTLA',
             'HUAZALINGO',
             'HUEHUETLA',
             'HUEJUTLA DE REYES',
             'HUICHAPAN',
             'IXMIQUILPAN',
             'JACALA DE LEDEZMA',
             'JALTOCAN',
             'JUAREZ HIDALGO',
             'LA MISION',
             'LOLOTLA',
             'METEPEC',
             'METZTITLAN',
             'MINERAL DE LA REFORMA',
             'MINERAL DEL CHICO',
             'MINERAL DEL MONTE',
             'MIXQUIAHUALA DE JUAREZ',
             'MOLANGO DE ESCAMILLA',
             'NICOLAS FLORES',
             'NOPALA DE VILLAGRAN',
             'OMITLAN DE JUAREZ',
             'PACHUCA DE SOTO',
             'PACULA',
             'PISAFLORES',
             'PROGRESO DE OBREGON',
             'SAN AGUSTIN METZQUITITLAN',
             'SAN AGUSTIN TLAXIACA',
             'SAN BARTOLO TUTOTEPEC',
             'SAN FELIPE ORIZATLAN',
             'SAN SALVADOR',
             'SANTIAGO DE ANAYA',
             'SANTIAGO TULANTEPEC DE LUGO GUERRERO',
             'SINGUILUCAN',
             'TASQUILLO',
             'TECOZAUTLA',
             'TENANGO DE DORIA',
             'TEPEAPULCO',
             'TEPEHUACAN DE GUERRERO',
             'TEPEJI DEL RIO DE OCAMPO',
             'TEPETITLAN',
             'TETEPANGO',
             'TEZONTEPEC DE ALDAMA',
             'TIANGUISTENGO',
             'TIZAYUCA',
             'TLAHUELILPAN',
             'TLAHUILTEPA',
             'TLANALAPA',
             'TLANCHINOL',
             'TLAXCOAPAN',
             'TOLCAYUCA',
             'TULA DE ALLENDE',
             'TULANCINGO DE BRAVO',
             'VILLA DE TEZONTEPEC',
             'XOCHIATIPAN',
             'XOCHICOATLAN',
             'YAHUALICA',
             'ZACUALTIPAN DE ANGELES',
             'ZAPOTLAN DE JUAREZ',
             'ZEMPOALA',
             'ZIMAPAN'
         ],
         'JALISCO' => [
             'ACATIC',
             'ACATLAN DE JUAREZ',
             'AHUALULCO DE MERCADO',
             'AMACUECA',
             'AMATITAN',
             'AMECA',
             'ARANDAS',
             'ATEMAJAC DE BRIZUELA',
             'ATENGO',
             'ATENGUILLO',
             'ATOTONILCO EL ALTO',
             'ATOYAC',
             'AUTLAN DE NAVARRO',
             'AYOTLAN',
             'AYUTLA',
             'BOLAÑOS',
             'CABO CORRIENTES',
             'CAÑADAS DE OBREGON',
             'CASIMIRO CASTILLO',
             'CHAPALA',
             'CHIMALTITAN',
             'CHIQUILISTLAN',
             'CIHUATLAN',
             'COLOTLAN',
             'CONCEPCION DE BUENOS AIRES',
             'CUAUTITLAN DE GARCIA BARRAGAN',
             'CUAUTLA',
             'CUQUIO',
             'DEGOLLADO',
             'EJUTLA',
             'EL GRULLO',
             'EL LIMON',
             'EL SALTO',
             'ENCARNACION DE DIAZ',
             'ETZATLAN',
             'GUACHINANGO',
             'GUADALAJARA',
             'HOSTOTIPAQUILLO',
             'HUEJUCAR',
             'HUEJUQUILLA EL ALTO',
             'IXTLAHUACAN DE LOS MEMBRILLOS',
             'IXTLAHUACAN DEL RIO',
             'JALOSTOTITLAN',
             'JAMAY',
             'JILOTLAN DE LOS DOLORES',
             'JOCOTEPEC',
             'JUANACATLAN',
             'JUCHITLAN',
             'LA BARCA',
             'LA HUERTA',
             'LA MANZANILLA DE LA PAZ',
             'LAGOS DE MORENO',
             'MAGDALENA',
             'MASCOTA',
             'MAZAMITLA',
             'MEXTICACAN',
             'MEZQUITIC',
             'MIXTLAN',
             'OCOTLAN',
             'OJUELOS DE JALISCO',
             'PIHUAMO',
             'PONCITLAN',
             'PUERTO VALLARTA',
             'QUITUPAN',
             'SAN CRISTOBAL DE LA BARRANCA',
             'SAN DIEGO DE ALEJANDRIA',
             'SAN GABRIEL',
             'SAN IGNACIO CERRO GORDO',
             'SAN JUAN DE LOS LAGOS',
             'SAN JUANITO DE ESCOBEDO',
             'SAN JULIAN',
             'SAN MARTIN DE BOLAÑOS',
             'SAN MARTIN HIDALGO',
             'SAN MIGUEL EL ALTO',
             'SAN PEDRO TLAQUEPAQUE',
             'SAN SEBASTIAN DEL OESTE',
             'SANTA MARIA DE LOS ANGELES',
             'SANTA MARIA DEL ORO',
             'SAYULA',
             'TALA',
             'TALPA DE ALLENDE',
             'TAMAZULA DE GORDIANO',
             'TAPALPA',
             'TECALITLAN',
             'TECHALUTA DE MONTENEGRO',
             'TECOLOTLAN',
             'TENAMAXTLAN',
             'TEOCALTICHE',
             'TEOCUITATLAN DE CORONA',
             'TEPATITLAN DE MORELOS',
             'TEQUILA',
             'TEUCHITLAN',
             'TIZAPAN EL ALTO',
             'TLAJOMULCO DE ZUÑIGA',
             'TOLIMAN',
             'TOMATLAN',
             'TONAYA',
             'TONILA',
             'TOTATICHE',
             'TOTOTLAN',
             'TUXCACUESCO',
             'TUXCUECA',
             'TUXPAN',
             'UNION DE SAN ANTONIO',
             'UNION DE TULA',
             'VALLE DE GUADALUPE',
             'VALLE DE JUAREZ',
             'VILLA CORONA',
             'VILLA GUERRERO',
             'VILLA HIDALGO',
             'VILLA PURIFICACION',
             'YAHUALICA DE GONZALEZ GALLO',
             'ZACOALCO DE TORRES',
             'ZAPOPAN',
             'ZAPOTILTIC',
             'ZAPOTITLAN DE VADILLO',
             'ZAPOTLAN DEL REY',
             'ZAPOTLAN EL GRANDE',
             'ZAPOTLANEJO'
         ],
         'MEXICO' => [
             'ACAMBAY',
             'ACOLMAN',
             'ACULCO',
             'ALMOLOYA DE ALQUISIRAS',
             'ALMOLOYA DE JUAREZ',
             'ALMOLOYA DEL RIO',
             'AMANALCO',
             'AMATEPEC',
             'AMECAMECA',
             'APAXCO',
             'ATENCO',
             'ATIZAPAN',
             'ATIZAPAN DE ZARAGOZA',
             'ATLACOMULCO',
             'ATLAUTLA',
             'AXAPUSCO',
             'AYAPANGO',
             'CALIMAYA',
             'CAPULHUAC',
             'CHALCO',
             'CHAPA DE MOTA',
             'CHAPULTEPEC',
             'CHIAUTLA',
             'CHICOLOAPAN',
             'CHICONCUAC',
             'CHIMALHUACAN',
             'COACALCO DE BERRIOZABAL',
             'COATEPEC HARINAS',
             'COCOTITLAN',
             'COYOTEPEC',
             'CUAUTITLAN',
             'CUAUTITLAN IZCALLI',
             'DONATO GUERRA',
             'ECATEPEC DE MORELOS',
             'ECATZINGO',
             'EL ORO',
             'HUEHUETOCA',
             'HUEYPOXTLA',
             'HUIXQUILUCAN',
             'ISIDRO FABELA',
             'IXTAPALUCA',
             'IXTAPAN DE LA SAL',
             'IXTAPAN DEL ORO',
             'IXTLAHUACA',
             'JALTENCO',
             'JILOTEPEC',
             'JILOTZINGO',
             'JIQUIPILCO',
             'JOCOTITLAN',
             'JOQUICINGO',
             'JUCHITEPEC',
             'LA PAZ',
             'LERMA',
             'LUVIANOS',
             'MALINALCO',
             'MELCHOR OCAMPO',
             'METEPEC',
             'MEXICALTZINGO',
             'MORELOS',
             'NAUCALPAN DE JUAREZ',
             'NEXTLALPAN',
             'NEZAHUALCOYOTL',
             'NICOLAS ROMERO',
             'NOPALTEPEC',
             'OCOYOACAC',
             'OCUILAN',
             'OTUMBA',
             'OTZOLOAPAN',
             'OTZOLOTEPEC',
             'OZUMBA',
             'PAPALOTLA',
             'POLOTITLAN',
             'RAYON',
             'SAN ANTONIO LA ISLA',
             'SAN FELIPE DEL PROGRESO',
             'SAN JOSE DEL RINCON',
             'SAN MARTIN DE LAS PIRAMIDES',
             'SAN MATEO ATENCO',
             'SAN SIMON DE GUERRERO',
             'SANTO TOMAS',
             'SOYANIQUILPAN DE JUAREZ',
             'SULTEPEC',
             'TECAMAC',
             'TEJUPILCO',
             'TEMAMATLA',
             'TEMASCALAPA',
             'TEMASCALCINGO',
             'TEMASCALTEPEC',
             'TEMOAYA',
             'TENANCINGO',
             'TENANGO DEL AIRE',
             'TENANGO DEL VALLE',
             'TEOLOYUCAN',
             'TEOTIHUACAN',
             'TEPETLAOXTOC',
             'TEPETLIXPA',
             'TEPOTZOTLAN',
             'TEQUIXQUIAC',
             'TEXCALTITLAN',
             'TEXCALYACAC',
             'TEXCOCO',
             'TEZOYUCA',
             'TIANGUISTENCO',
             'TIMILPAN',
             'TLALMANALCO',
             'TLALNEPANTLA DE BAZ',
             'TLATLAYA',
             'TOLUCA',
             'TONANITLA',
             'TONATICO',
             'TULTEPEC',
             'TULTITLAN',
             'VALLE DE BRAVO',
             'VALLE DE CHALCO SOLIDARIDAD',
             'VILLA DE ALLENDE',
             'VILLA DEL CARBON',
             'VILLA GUERRERO',
             'VILLA VICTORIA',
             'XALATLACO',
             'XONACATLAN',
             'ZACAZONAPAN',
             'ZACUALPAN',
             'ZINACANTEPEC',
             'ZUMPAHUACAN',
             'ZUMPANGO',
         ],
         'MICHOACAN' => [
             'ACUITZIO',
             'AGUILILLA',
             'ANGAMACUTIRO',
             'ANGANGUEO',
             'APATZINGAN',
             'APORO',
             'AQUILA',
             'ARIO',
             'BRISEÑAS',
             'BUENAVISTA',
             'CARACUARO',
             'CHARAPAN',
             'CHARO',
             'CHAVINDA',
             'CHERAN',
             'CHILCHOTA',
             'CHINICUILA',
             'CHUCANDIRO',
             'CHURINTZIO',
             'CHURUMUCO',
             'COAHUAYANA',
             'COALCOMAN DE VAZQUEZ PALLARES',
             'COENEO',
             'COJUMATLAN DE REGULES',
             'CONTEPEC',
             'COPANDARO',
             'COTIJA',
             'CUITZEO',
             'ECUANDUREO',
             'EPITACIO HUERTA',
             'ERONGARICUARO',
             'GABRIEL ZAMORA',
             'HUANDACAREO',
             'HUANIQUEO',
             'HUETAMO',
             'HUIRAMBA',
             'INDAPARAPEO',
             'IRIMBO',
             'IXTLAN',
             'JACONA',
             'JIQUILPAN',
             'JOSE SIXTO VERDUZCO',
             'JUNGAPEO',
             'LA HUACANA',
             'LA PIEDAD',
             'LAGUNILLAS',
             'LAZARO CARDENAS',
             'LOS REYES',
             'MADERO',
             'MARAVATIO',
             'MARCOS CASTELLANOS',
             'MORELIA',
             'MUGICA',
             'NAHUATZEN',
             'NOCUPETARO',
             'NUEVO PARANGARICUTIRO',
             'NUEVO URECHO',
             'NUMARAN',
             'PAJACUARAN',
             'PANINDICUARO',
             'PARACHO',
             'PARACUARO',
             'PATZCUARO',
             'PENJAMILLO',
             'PERIBAN',
             'PUREPERO',
             'PURUANDIRO',
             'QUERENDARO',
             'QUIROGA',
             'SAHUAYO',
             'SALVADOR ESCALANTE',
             'SANTA ANA MAYA',
             'SENGUIO',
             'SUSUPUATO',
             'TACAMBARO',
             'TANCITARO',
             'TANGAMANDAPIO',
             'TANGANCICUARO',
             'TANHUATO',
             'TARETAN',
             'TARIMBARO',
             'TEPALCATEPEC',
             'TINGAMBATO',
             'TINGÜINDIN',
             'TIQUICHEO DE NICOLAS ROMERO',
             'TLALPUJAHUA',
             'TLAZAZALCA',
             'TOCUMBO',
             'TUMBISCATIO',
             'TURICATO',
             'TUZANTLA',
             'TZINTZUNTZAN',
             'TZITZIO',
             'URUAPAN',
             'VILLAMAR',
             'VISTA HERMOSA',
             'YURECUARO',
             'ZACAPU',
             'ZAMORA',
             'ZINAPARO',
             'ZINAPECUARO',
             'ZIRACUARETIRO',
             'ZITACUARO'
         ],
         'MORELOS' => [
             'AMACUZAC',
             'ATLATLAHUCAN',
             'AXOCHIAPAN',
             'AYALA',
             'COATLAN DEL RIO',
             'CUAUTLA',
             'CUERNAVACA',
             'HUITZILAC',
             'JANTETELCO',
             'JIUTEPEC',
             'JOJUTLA',
             'JONACATEPEC',
             'MAZATEPEC',
             'MIACATLAN',
             'OCUITUCO',
             'PUENTE DE IXTLA',
             'TEMIXCO',
             'TEMOAC',
             'TEPALCINGO',
             'TEPOZTLAN',
             'TETECALA',
             'TETELA DEL VOLCAN',
             'TLALNEPANTLA',
             'TLALTIZAPAN DE ZAPATA',
             'TLAQUILTENANGO',
             'TLAYACAPAN',
             'TOTOLAPAN',
             'XOCHITEPEC',
             'YAUTEPEC',
             'YECAPIXTLA',
             'ZACATEPEC',
             'ZACUALPAN DE AMILPAS'
         ],
         'NAYARIT' => [
             'ACAPONETA',
             'AHUACATLAN',
             'AMATLAN DE CAÑAS',
             'BAHIA DE BANDERAS',
             'COMPOSTELA',
             'DEL NAYAR',
             'HUAJICORI',
             'IXTLAN DEL RIO',
             'JALA',
             'LA YESCA',
             'ROSAMORADA',
             'RUIZ',
             'SAN BLAS',
             'SAN PEDRO LAGUNILLAS',
             'SANTIAGO IXCUINTLA',
             'TECUALA',
             'TEPIC',
             'XALISCO'
         ],
         'NUEVO LEON' => [
             'AGUALEGUAS',
             'ANAHUAC',
             'APODACA',
             'ARAMBERRI',
             'BUSTAMANTE',
             'CADEREYTA JIMENEZ',
             'CERRALVO',
             'CHINA',
             'CIENEGA DE FLORES',
             'DR. ARROYO',
             'DR. COSS',
             'DR. GONZALEZ',
             'GARCIA',
             'GRAL. BRAVO',
             'GRAL. ESCOBEDO',
             'GRAL. TERAN',
             'GRAL. TREVIÑO',
             'GRAL. ZARAGOZA',
             'GRAL. ZUAZUA',
             'HIGUERAS',
             'HUALAHUISES',
             'ITURBIDE',
             'LAMPAZOS DE NARANJO',
             'LINARES',
             'LOS ALDAMAS',
             'LOS HERRERAS',
             'LOS RAMONES',
             'MARIN',
             'MIER Y NORIEGA',
             'MINA',
             'MONTEMORELOS',
             'MONTERREY',
             'PARAS',
             'PESQUERIA',
             'RAYONES',
             'SABINAS HIDALGO',
             'SALINAS VICTORIA',
             'SAN NICOLAS DE LOS GARZA',
             'SAN PEDRO GARZA GARCIA',
             'SANTIAGO',
             'VALLECILLO',
             'VILLALDAMA'
         ],
         'OAXACA' => [
             'ABEJONES',
             'ACATLAN DE PEREZ FIGUEROA',
             'ANIMAS TRUJANO',
             'ASUNCION CACALOTEPEC',
             'ASUNCION CUYOTEPEJI',
             'ASUNCION IXTALTEPEC',
             'ASUNCION NOCHIXTLAN',
             'ASUNCION OCOTLAN',
             'ASUNCION TLACOLULITA',
             'AYOQUEZCO DE ALDAMA',
             'AYOTZINTEPEC',
             'CALIHUALA',
             'CANDELARIA LOXICHA',
             'CAPULALPAM DE MENDEZ',
             'CHAHUITES',
             'CHALCATONGO DE HIDALGO',
             'CHIQUIHUITLAN DE BENITO JUAREZ',
             'CIENEGA DE ZIMATLAN',
             'CIUDAD IXTEPEC',
             'COATECAS ALTAS',
             'COICOYAN DE LAS FLORES',
             'CONCEPCION BUENAVISTA',
             'CONCEPCION PAPALO',
             'CONSTANCIA DEL ROSARIO',
             'COSOLAPA',
             'COSOLTEPEC',
             'CUILAPAM DE GUERRERO',
             'CUYAMECALCO VILLA DE ZARAGOZA',
             'EL BARRIO DE LA SOLEDAD',
             'EL ESPINAL',
             'ELOXOCHITLAN DE FLORES MAGON',
             'FRESNILLO DE TRUJANO',
             'GUADALUPE DE RAMIREZ',
             'GUADALUPE ETLA',
             'GUELATAO DE JUAREZ',
             'GUEVEA DE HUMBOLDT',
             'H VILLA TEZOATLAN SEGURA Y LUNA CUNA IND OAX',
             'HEROICA CIUDAD DE EJUTLA DE CRESPO',
             'HEROICA CIUDAD DE HUAJUAPAN DE LEON',
             'HEROICA CIUDAD DE JUCHITAN DE ZARAGOZA',
             'HEROICA CIUDAD DE TLAXIACO',
             'HUAUTEPEC',
             'HUAUTLA DE JIMENEZ',
             'IXPANTEPEC NIEVES',
             'IXTLAN DE JUAREZ',
             'LA COMPAÑIA',
             'LA PE',
             'LA REFORMA',
             'LA TRINIDAD VISTA HERMOSA',
             'LOMA BONITA',
             'MAGDALENA APASCO',
             'MAGDALENA JALTEPEC',
             'MAGDALENA MIXTEPEC',
             'MAGDALENA OCOTLAN',
             'MAGDALENA PEÑASCO',
             'MAGDALENA TEITIPAC',
             'MAGDALENA TEQUISISTLAN',
             'MAGDALENA TLACOTEPEC',
             'MAGDALENA YODOCONO DE PORFIRIO DIAZ',
             'MAGDALENA ZAHUATLAN',
             'MARISCALA DE JUAREZ',
             'MARTIRES DE TACUBAYA',
             'MATIAS ROMERO AVENDAÑO',
             'MAZATLAN VILLA DE FLORES',
             'MESONES HIDALGO',
             'MIAHUATLAN DE PORFIRIO DIAZ',
             'MIXISTLAN DE LA REFORMA',
             'MONJAS',
             'NATIVIDAD',
             'NAZARENO ETLA',
             'NEJAPA DE MADERO',
             'NUEVO ZOQUIAPAM',
             'OAXACA DE JUAREZ',
             'OCOTLAN DE MORELOS',
             'PINOTEPA DE DON LUIS',
             'PLUMA HIDALGO',
             'PUTLA VILLA DE GUERRERO',
             'REFORMA DE PINEDA',
             'REYES ETLA',
             'ROJAS DE CUAUHTEMOC',
             'SALINA CRUZ',
             'SAN AGUSTIN AMATENGO',
             'SAN AGUSTIN ATENANGO',
             'SAN AGUSTIN CHAYUCO',
             'SAN AGUSTIN DE LAS JUNTAS',
             'SAN AGUSTIN ETLA',
             'SAN AGUSTIN LOXICHA',
             'SAN AGUSTIN TLACOTEPEC',
             'SAN AGUSTIN YATARENI',
             'SAN ANDRES CABECERA NUEVA',
             'SAN ANDRES DINICUITI',
             'SAN ANDRES HUAXPALTEPEC',
             'SAN ANDRES HUAYAPAM',
             'SAN ANDRES IXTLAHUACA',
             'SAN ANDRES LAGUNAS',
             'SAN ANDRES NUXIÑO',
             'SAN ANDRES PAXTLAN',
             'SAN ANDRES SINAXTLA',
             'SAN ANDRES SOLAGA',
             'SAN ANDRES TEOTILALPAM',
             'SAN ANDRES TEPETLAPA',
             'SAN ANDRES YAA',
             'SAN ANDRES ZABACHE',
             'SAN ANDRES ZAUTLA',
             'SAN ANTONINO CASTILLO VELASCO',
             'SAN ANTONINO EL ALTO',
             'SAN ANTONINO MONTE VERDE',
             'SAN ANTONIO ACUTLA',
             'SAN ANTONIO DE LA CAL',
             'SAN ANTONIO HUITEPEC',
             'SAN ANTONIO NANAHUATIPAM',
             'SAN ANTONIO SINICAHUA',
             'SAN ANTONIO TEPETLAPA',
             'SAN BALTAZAR CHICHICAPAM',
             'SAN BALTAZAR LOXICHA',
             'SAN BALTAZAR YATZACHI EL BAJO',
             'SAN BARTOLO COYOTEPEC',
             'SAN BARTOLO SOYALTEPEC',
             'SAN BARTOLO YAUTEPEC',
             'SAN BARTOLOME AYAUTLA',
             'SAN BARTOLOME LOXICHA',
             'SAN BARTOLOME QUIALANA',
             'SAN BARTOLOME YUCUAÑE',
             'SAN BARTOLOME ZOOGOCHO',
             'SAN BERNARDO MIXTEPEC',
             'SAN BLAS ATEMPA',
             'SAN CARLOS YAUTEPEC',
             'SAN CRISTOBAL AMATLAN',
             'SAN CRISTOBAL AMOLTEPEC',
             'SAN CRISTOBAL LACHIRIOAG',
             'SAN CRISTOBAL SUCHIXTLAHUACA',
             'SAN DIONISIO DEL MAR',
             'SAN DIONISIO OCOTEPEC',
             'SAN DIONISIO OCOTLAN',
             'SAN ESTEBAN ATATLAHUCA',
             'SAN FELIPE JALAPA DE DIAZ',
             'SAN FELIPE TEJALAPAM',
             'SAN FELIPE USILA',
             'SAN FRANCISCO CAHUACUA',
             'SAN FRANCISCO CAJONOS',
             'SAN FRANCISCO CHAPULAPA',
             'SAN FRANCISCO CHINDUA',
             'SAN FRANCISCO DEL MAR',
             'SAN FRANCISCO HUEHUETLAN',
             'SAN FRANCISCO IXHUATAN',
             'SAN FRANCISCO JALTEPETONGO',
             'SAN FRANCISCO LACHIGOLO',
             'SAN FRANCISCO LOGUECHE',
             'SAN FRANCISCO NUXAÑO',
             'SAN FRANCISCO OZOLOTEPEC',
             'SAN FRANCISCO SOLA',
             'SAN FRANCISCO TELIXTLAHUACA',
             'SAN FRANCISCO TEOPAN',
             'SAN FRANCISCO TLAPANCINGO',
             'SAN GABRIEL MIXTEPEC',
             'SAN ILDEFONSO AMATLAN',
             'SAN ILDEFONSO SOLA',
             'SAN ILDEFONSO VILLA ALTA',
             'SAN JACINTO AMILPAS',
             'SAN JACINTO TLACOTEPEC',
             'SAN JERONIMO COATLAN',
             'SAN JERONIMO SILACAYOAPILLA',
             'SAN JERONIMO SOSOLA',
             'SAN JERONIMO TAVICHE',
             'SAN JERONIMO TECOATL',
             'SAN JERONIMO TLACOCHAHUAYA',
             'SAN JORGE NUCHITA',
             'SAN JOSE AYUQUILA',
             'SAN JOSE CHILTEPEC',
             'SAN JOSE DEL PEÑASCO',
             'SAN JOSE DEL PROGRESO',
             'SAN JOSE ESTANCIA GRANDE',
             'SAN JOSE INDEPENDENCIA',
             'SAN JOSE LACHIGUIRI',
             'SAN JOSE TENANGO',
             'SAN JUAN ACHIUTLA',
             'SAN JUAN ATEPEC',
             'SAN JUAN BAUTISTA ATATLAHUCA',
             'SAN JUAN BAUTISTA COIXTLAHUACA',
             'SAN JUAN BAUTISTA CUICATLAN',
             'SAN JUAN BAUTISTA GUELACHE',
             'SAN JUAN BAUTISTA JAYACATLAN',
             'SAN JUAN BAUTISTA LO DE SOTO',
             'SAN JUAN BAUTISTA SUCHITEPEC',
             'SAN JUAN BAUTISTA TLACHICHILCO',
             'SAN JUAN BAUTISTA TLACOATZINTEPEC',
             'SAN JUAN BAUTISTA TUXTEPEC',
             'SAN JUAN BAUTISTA VALLE NACIONAL',
             'SAN JUAN CACAHUATEPEC',
             'SAN JUAN CHICOMEZUCHIL',
             'SAN JUAN CHILATECA',
             'SAN JUAN CIENEGUILLA',
             'SAN JUAN COATZOSPAM',
             'SAN JUAN COLORADO',
             'SAN JUAN COMALTEPEC',
             'SAN JUAN COTZOCON',
             'SAN JUAN DE LOS CUES',
             'SAN JUAN DEL ESTADO',
             'SAN JUAN DIUXI',
             'SAN JUAN EVANGELISTA ANALCO',
             'SAN JUAN GUELAVIA',
             'SAN JUAN GUICHICOVI',
             'SAN JUAN IHUALTEPEC',
             'SAN JUAN JUQUILA MIXES',
             'SAN JUAN JUQUILA VIJANOS',
             'SAN JUAN LACHAO',
             'SAN JUAN LACHIGALLA',
             'SAN JUAN LAJARCIA',
             'SAN JUAN LALANA',
             'SAN JUAN MAZATLAN',
             'SAN JUAN MIXTEPEC',
             'SAN JUAN ÑUMI',
             'SAN JUAN OZOLOTEPEC',
             'SAN JUAN PETLAPA',
             'SAN JUAN QUIAHIJE',
             'SAN JUAN QUIOTEPEC',
             'SAN JUAN SAYULTEPEC',
             'SAN JUAN TABAA',
             'SAN JUAN TAMAZOLA',
             'SAN JUAN TEITA',
             'SAN JUAN TEITIPAC',
             'SAN JUAN TEPEUXILA',
             'SAN JUAN TEPOSCOLULA',
             'SAN JUAN YAEE',
             'SAN JUAN YATZONA',
             'SAN JUAN YUCUITA',
             'SAN LORENZO',
             'SAN LORENZO ALBARRADAS',
             'SAN LORENZO CACAOTEPEC',
             'SAN LORENZO CUAUNECUILTITLA',
             'SAN LORENZO TEXMELUCAN',
             'SAN LORENZO VICTORIA',
             'SAN LUCAS CAMOTLAN',
             'SAN LUCAS OJITLAN',
             'SAN LUCAS QUIAVINI',
             'SAN LUCAS ZOQUIAPAM',
             'SAN LUIS AMATLAN',
             'SAN MARCIAL OZOLOTEPEC',
             'SAN MARCOS ARTEAGA',
             'SAN MARTIN DE LOS CANSECOS',
             'SAN MARTIN HUAMELULPAM',
             'SAN MARTIN ITUNYOSO',
             'SAN MARTIN LACHILA',
             'SAN MARTIN PERAS',
             'SAN MARTIN TILCAJETE',
             'SAN MARTIN TOXPALAN',
             'SAN MARTIN ZACATEPEC',
             'SAN MATEO CAJONOS',
             'SAN MATEO DEL MAR',
             'SAN MATEO ETLATONGO',
             'SAN MATEO NEJAPAM',
             'SAN MATEO PEÑASCO',
             'SAN MATEO PIÑAS',
             'SAN MATEO RIO HONDO',
             'SAN MATEO SINDIHUI',
             'SAN MATEO TLAPILTEPEC',
             'SAN MATEO YOLOXOCHITLAN',
             'SAN MATEO YUCUTINDOO',
             'SAN MELCHOR BETAZA',
             'SAN MIGUEL ACHIUTLA',
             'SAN MIGUEL AHUEHUETITLAN',
             'SAN MIGUEL ALOAPAM',
             'SAN MIGUEL AMATITLAN',
             'SAN MIGUEL AMATLAN',
             'SAN MIGUEL CHICAHUA',
             'SAN MIGUEL CHIMALAPA',
             'SAN MIGUEL COATLAN',
             'SAN MIGUEL DEL PUERTO',
             'SAN MIGUEL DEL RIO',
             'SAN MIGUEL EJUTLA',
             'SAN MIGUEL EL GRANDE',
             'SAN MIGUEL HUAUTLA',
             'SAN MIGUEL MIXTEPEC',
             'SAN MIGUEL PANIXTLAHUACA',
             'SAN MIGUEL PERAS',
             'SAN MIGUEL PIEDRAS',
             'SAN MIGUEL QUETZALTEPEC',
             'SAN MIGUEL SANTA FLOR',
             'SAN MIGUEL SOYALTEPEC',
             'SAN MIGUEL SUCHIXTEPEC',
             'SAN MIGUEL TECOMATLAN',
             'SAN MIGUEL TENANGO',
             'SAN MIGUEL TEQUIXTEPEC',
             'SAN MIGUEL TILQUIAPAM',
             'SAN MIGUEL TLACAMAMA',
             'SAN MIGUEL TLACOTEPEC',
             'SAN MIGUEL TULANCINGO',
             'SAN MIGUEL YOTAO',
             'SAN NICOLAS',
             'SAN NICOLAS HIDALGO',
             'SAN PABLO COATLAN',
             'SAN PABLO CUATRO VENADOS',
             'SAN PABLO ETLA',
             'SAN PABLO HUITZO',
             'SAN PABLO HUIXTEPEC',
             'SAN PABLO MACUILTIANGUIS',
             'SAN PABLO TIJALTEPEC',
             'SAN PABLO VILLA DE MITLA',
             'SAN PABLO YAGANIZA',
             'SAN PEDRO AMUZGOS',
             'SAN PEDRO APOSTOL',
             'SAN PEDRO ATOYAC',
             'SAN PEDRO CAJONOS',
             'SAN PEDRO COMITANCILLO',
             'SAN PEDRO COXCALTEPEC CANTAROS',
             'SAN PEDRO EL ALTO',
             'SAN PEDRO HUAMELULA',
             'SAN PEDRO HUILOTEPEC',
             'SAN PEDRO IXCATLAN',
             'SAN PEDRO IXTLAHUACA',
             'SAN PEDRO JALTEPETONGO',
             'SAN PEDRO JICAYAN',
             'SAN PEDRO JOCOTIPAC',
             'SAN PEDRO JUCHATENGO',
             'SAN PEDRO MARTIR',
             'SAN PEDRO MARTIR QUIECHAPA',
             'SAN PEDRO MARTIR YUCUXACO',
             'SAN PEDRO MIXTEPEC',
             'SAN PEDRO MOLINOS',
             'SAN PEDRO NOPALA',
             'SAN PEDRO OCOPETATILLO',
             'SAN PEDRO OCOTEPEC',
             'SAN PEDRO POCHUTLA',
             'SAN PEDRO QUIATONI',
             'SAN PEDRO SOCHIAPAM',
             'SAN PEDRO TAPANATEPEC',
             'SAN PEDRO TAVICHE',
             'SAN PEDRO TEOZACOALCO',
             'SAN PEDRO TEUTILA',
             'SAN PEDRO TIDAA',
             'SAN PEDRO TOPILTEPEC',
             'SAN PEDRO TOTOLAPAM',
             'SAN PEDRO Y SAN PABLO AYUTLA',
             'SAN PEDRO Y SAN PABLO TEPOSCOLULA',
             'SAN PEDRO Y SAN PABLO TEQUIXTEPEC',
             'SAN PEDRO YANERI',
             'SAN PEDRO YOLOX',
             'SAN PEDRO YUCUNAMA',
             'SAN RAYMUNDO JALPAN',
             'SAN SEBASTIAN ABASOLO',
             'SAN SEBASTIAN COATLAN',
             'SAN SEBASTIAN IXCAPA',
             'SAN SEBASTIAN NICANANDUTA',
             'SAN SEBASTIAN RIO HONDO',
             'SAN SEBASTIAN TECOMAXTLAHUACA',
             'SAN SEBASTIAN TEITIPAC',
             'SAN SEBASTIAN TUTLA',
             'SAN SIMON ALMOLONGAS',
             'SAN SIMON ZAHUATLAN',
             'SAN VICENTE COATLAN',
             'SAN VICENTE LACHIXIO',
             'SAN VICENTE NUÑU',
             'SANTA ANA',
             'SANTA ANA ATEIXTLAHUACA',
             'SANTA ANA CUAUHTEMOC',
             'SANTA ANA DEL VALLE',
             'SANTA ANA TAVELA',
             'SANTA ANA TLAPACOYAN',
             'SANTA ANA YARENI',
             'SANTA ANA ZEGACHE',
             'SANTA CATALINA QUIERI',
             'SANTA CATARINA CUIXTLA',
             'SANTA CATARINA IXTEPEJI',
             'SANTA CATARINA JUQUILA',
             'SANTA CATARINA LACHATAO',
             'SANTA CATARINA LOXICHA',
             'SANTA CATARINA MECHOACAN',
             'SANTA CATARINA MINAS',
             'SANTA CATARINA QUIANE',
             'SANTA CATARINA QUIOQUITANI',
             'SANTA CATARINA TAYATA',
             'SANTA CATARINA TICUA',
             'SANTA CATARINA YOSONOTU',
             'SANTA CATARINA ZAPOQUILA',
             'SANTA CRUZ ACATEPEC',
             'SANTA CRUZ AMILPAS',
             'SANTA CRUZ DE BRAVO',
             'SANTA CRUZ ITUNDUJIA',
             'SANTA CRUZ MIXTEPEC',
             'SANTA CRUZ NUNDACO',
             'SANTA CRUZ PAPALUTLA',
             'SANTA CRUZ TACACHE DE MINA',
             'SANTA CRUZ TACAHUA',
             'SANTA CRUZ TAYATA',
             'SANTA CRUZ XITLA',
             'SANTA CRUZ XOXOCOTLAN',
             'SANTA CRUZ ZENZONTEPEC',
             'SANTA GERTRUDIS',
             'SANTA INES DE ZARAGOZA',
             'SANTA INES DEL MONTE',
             'SANTA INES YATZECHE',
             'SANTA LUCIA DEL CAMINO',
             'SANTA LUCIA MIAHUATLAN',
             'SANTA LUCIA MONTEVERDE',
             'SANTA LUCIA OCOTLAN',
             'SANTA MAGDALENA JICOTLAN',
             'SANTA MARIA ALOTEPEC',
             'SANTA MARIA APAZCO',
             'SANTA MARIA ATZOMPA',
             'SANTA MARIA CAMOTLAN',
             'SANTA MARIA CHACHOAPAM',
             'SANTA MARIA CHILCHOTLA',
             'SANTA MARIA CHIMALAPA',
             'SANTA MARIA COLOTEPEC',
             'SANTA MARIA CORTIJO',
             'SANTA MARIA COYOTEPEC',
             'SANTA MARIA DEL ROSARIO',
             'SANTA MARIA DEL TULE',
             'SANTA MARIA ECATEPEC',
             'SANTA MARIA GUELACE',
             'SANTA MARIA GUIENAGATI',
             'SANTA MARIA HUATULCO',
             'SANTA MARIA HUAZOLOTITLAN',
             'SANTA MARIA IPALAPA',
             'SANTA MARIA IXCATLAN',
             'SANTA MARIA JACATEPEC',
             'SANTA MARIA JALAPA DEL MARQUES',
             'SANTA MARIA JALTIANGUIS',
             'SANTA MARIA LA ASUNCION',
             'SANTA MARIA LACHIXIO',
             'SANTA MARIA MIXTEQUILLA',
             'SANTA MARIA NATIVITAS',
             'SANTA MARIA NDUAYACO',
             'SANTA MARIA OZOLOTEPEC',
             'SANTA MARIA PAPALO',
             'SANTA MARIA PEÑOLES',
             'SANTA MARIA PETAPA',
             'SANTA MARIA QUIEGOLANI',
             'SANTA MARIA SOLA',
             'SANTA MARIA TATALTEPEC',
             'SANTA MARIA TECOMAVACA',
             'SANTA MARIA TEMAXCALAPA',
             'SANTA MARIA TEMAXCALTEPEC',
             'SANTA MARIA TEOPOXCO',
             'SANTA MARIA TEPANTLALI',
             'SANTA MARIA TEXCATITLAN',
             'SANTA MARIA TLAHUITOLTEPEC',
             'SANTA MARIA TLALIXTAC',
             'SANTA MARIA TONAMECA',
             'SANTA MARIA TOTOLAPILLA',
             'SANTA MARIA XADANI',
             'SANTA MARIA YALINA',
             'SANTA MARIA YAVESIA',
             'SANTA MARIA YOLOTEPEC',
             'SANTA MARIA YOSOYUA',
             'SANTA MARIA YUCUHITI',
             'SANTA MARIA ZACATEPEC',
             'SANTA MARIA ZANIZA',
             'SANTA MARIA ZOQUITLAN',
             'SANTIAGO AMOLTEPEC',
             'SANTIAGO APOALA',
             'SANTIAGO APOSTOL',
             'SANTIAGO ASTATA',
             'SANTIAGO ATITLAN',
             'SANTIAGO AYUQUILILLA',
             'SANTIAGO CACALOXTEPEC',
             'SANTIAGO CAMOTLAN',
             'SANTIAGO CHAZUMBA',
             'SANTIAGO CHOAPAM',
             'SANTIAGO COMALTEPEC',
             'SANTIAGO DEL RIO',
             'SANTIAGO HUAJOLOTITLAN',
             'SANTIAGO HUAUCLILLA',
             'SANTIAGO IHUITLAN PLUMAS',
             'SANTIAGO IXCUINTEPEC',
             'SANTIAGO IXTAYUTLA',
             'SANTIAGO JAMILTEPEC',
             'SANTIAGO JOCOTEPEC',
             'SANTIAGO JUXTLAHUACA',
             'SANTIAGO LACHIGUIRI',
             'SANTIAGO LALOPA',
             'SANTIAGO LAOLLAGA',
             'SANTIAGO LAXOPA',
             'SANTIAGO LLANO GRANDE',
             'SANTIAGO MATATLAN',
             'SANTIAGO MILTEPEC',
             'SANTIAGO MINAS',
             'SANTIAGO NACALTEPEC',
             'SANTIAGO NEJAPILLA',
             'SANTIAGO NILTEPEC',
             'SANTIAGO NUNDICHE',
             'SANTIAGO NUYOO',
             'SANTIAGO PINOTEPA NACIONAL',
             'SANTIAGO SUCHILQUITONGO',
             'SANTIAGO TAMAZOLA',
             'SANTIAGO TAPEXTLA',
             'SANTIAGO TENANGO',
             'SANTIAGO TEPETLAPA',
             'SANTIAGO TETEPEC',
             'SANTIAGO TEXCALCINGO',
             'SANTIAGO TEXTITLAN',
             'SANTIAGO TILANTONGO',
             'SANTIAGO TILLO',
             'SANTIAGO TLAZOYALTEPEC',
             'SANTIAGO XANICA',
             'SANTIAGO XIACUI',
             'SANTIAGO YAITEPEC',
             'SANTIAGO YAVEO',
             'SANTIAGO YOLOMECATL',
             'SANTIAGO YOSONDUA',
             'SANTIAGO YUCUYACHI',
             'SANTIAGO ZACATEPEC',
             'SANTIAGO ZOOCHILA',
             'SANTO DOMINGO ALBARRADAS',
             'SANTO DOMINGO ARMENTA',
             'SANTO DOMINGO CHIHUITAN',
             'SANTO DOMINGO DE MORELOS',
             'SANTO DOMINGO INGENIO',
             'SANTO DOMINGO IXCATLAN',
             'SANTO DOMINGO NUXAA',
             'SANTO DOMINGO OZOLOTEPEC',
             'SANTO DOMINGO PETAPA',
             'SANTO DOMINGO ROAYAGA',
             'SANTO DOMINGO TEHUANTEPEC',
             'SANTO DOMINGO TEOJOMULCO',
             'SANTO DOMINGO TEPUXTEPEC',
             'SANTO DOMINGO TLATAYAPAM',
             'SANTO DOMINGO TOMALTEPEC',
             'SANTO DOMINGO TONALA',
             'SANTO DOMINGO TONALTEPEC',
             'SANTO DOMINGO XAGACIA',
             'SANTO DOMINGO YANHUITLAN',
             'SANTO DOMINGO YODOHINO',
             'SANTO DOMINGO ZANATEPEC',
             'SANTO TOMAS JALIEZA',
             'SANTO TOMAS MAZALTEPEC',
             'SANTO TOMAS OCOTEPEC',
             'SANTO TOMAS TAMAZULAPAN',
             'SANTOS REYES NOPALA',
             'SANTOS REYES PAPALO',
             'SANTOS REYES TEPEJILLO',
             'SANTOS REYES YUCUNA',
             'SILACAYOAPAM',
             'SITIO DE XITLAPEHUA',
             'SOLEDAD ETLA',
             'TAMAZULAPAM DEL ESPIRITU SANTO',
             'TANETZE DE ZARAGOZA',
             'TANICHE',
             'TATALTEPEC DE VALDES',
             'TEOCOCUILCO DE MARCOS PEREZ',
             'TEOTITLAN DE FLORES MAGON',
             'TEOTITLAN DEL VALLE',
             'TEOTONGO',
             'TEPELMEME VILLA DE MORELOS',
             'TLACOLULA DE MATAMOROS',
             'TLACOTEPEC PLUMAS',
             'TLALIXTAC DE CABRERA',
             'TOTONTEPEC VILLA DE MORELOS',
             'TRINIDAD ZAACHILA',
             'UNION HIDALGO',
             'VALERIO TRUJANO',
             'VILLA DE CHILAPA DE DIAZ',
             'VILLA DE ETLA',
             'VILLA DE TAMAZULAPAM DEL PROGRESO',
             'VILLA DE TUTUTEPEC DE MELCHOR OCAMPO',
             'VILLA DE ZAACHILA',
             'VILLA DIAZ ORDAZ',
             'VILLA SOLA DE VEGA',
             'VILLA TALEA DE CASTRO',
             'VILLA TEJUPAM DE LA UNION',
             'YAXE',
             'YOGANA',
             'YUTANDUCHI DE GUERRERO',
             'ZAPOTITLAN LAGUNAS',
             'ZAPOTITLAN PALMAS',
             'ZIMATLAN DE ALVAREZ'
         ],
         'PUEBLA' => [
             'ACAJETE',
             'ACATENO',
             'ACATZINGO',
             'ACTEOPAN',
             'AHUATLAN',
             'AHUAZOTEPEC',
             'AHUEHUETITLA',
             'AJALPAN',
             'ALBINO ZERTUCHE',
             'ALJOJUCA',
             'ALTEPEXI',
             'AMIXTLAN',
             'AMOZOC',
             'AQUIXTLA',
             'ATEMPAN',
             'ATEXCAL',
             'ATLEQUIZAYAN',
             'ATLIXCO',
             'ATOYATEMPAN',
             'ATZALA',
             'ATZITZIHUACAN',
             'ATZITZINTLA',
             'AXUTLA',
             'AYOTOXCO DE GUERRERO',
             'CALPAN',
             'CALTEPEC',
             'CAMOCUAUTLA',
             'CAÑADA MORELOS',
             'CAXHUACAN',
             'CHALCHICOMULA DE SESMA',
             'CHAPULCO',
             'CHIAUTZINGO',
             'CHICHIQUILA',
             'CHICONCUAUTLA',
             'CHIETLA',
             'CHIGMECATITLAN',
             'CHIGNAHUAPAN',
             'CHIGNAUTLA',
             'CHILA',
             'CHILA DE LA SAL',
             'CHILCHOTLA',
             'CHINANTLA',
             'COATEPEC',
             'COATZINGO',
             'COHETZALA',
             'COHUECAN',
             'CORONANGO',
             'COXCATLAN',
             'COYOMEAPAN',
             'CUAPIAXTLA DE MADERO',
             'CUAUTEMPAN',
             'CUAUTINCHAN',
             'CUAUTLANCINGO',
             'CUAYUCA DE ANDRADE',
             'CUETZALAN DEL PROGRESO',
             'CUYOACO',
             'DOMINGO ARENAS',
             'EPATLAN',
             'ESPERANZA',
             'FRANCISCO Z. MENA',
             'GENERAL FELIPE ANGELES',
             'HERMENEGILDO GALEANA',
             'HONEY',
             'HUAQUECHULA',
             'HUATLATLAUCA',
             'HUAUCHINANGO',
             'HUEHUETLAN EL CHICO',
             'HUEHUETLAN EL GRANDE',
             'HUEJOTZINGO',
             'HUEYAPAN',
             'HUEYTAMALCO',
             'HUEYTLALPAN',
             'HUITZILAN DE SERDAN',
             'HUITZILTEPEC',
             'IXCAMILPA DE GUERRERO',
             'IXCAQUIXTLA',
             'IXTACAMAXTITLAN',
             'IXTEPEC',
             'IZUCAR DE MATAMOROS',
             'JALPAN',
             'JOLALPAN',
             'JONOTLA',
             'JOPALA',
             'JUAN C. BONILLA',
             'JUAN GALINDO',
             'JUAN N. MENDEZ',
             'LA MAGDALENA TLATLAUQUITEPEC',
             'LAFRAGUA',
             'LIBRES',
             'LOS REYES DE JUAREZ',
             'MAZAPILTEPEC DE JUAREZ',
             'MIXTLA',
             'MOLCAXAC',
             'NAUPAN',
             'NAUZONTLA',
             'NEALTICAN',
             'NICOLAS BRAVO',
             'NOPALUCAN',
             'OCOYUCAN',
             'OLINTLA',
             'ORIENTAL',
             'PAHUATLAN',
             'PALMAR DE BRAVO',
             'PETLALCINGO',
             'PIAXTLA',
             'PUEBLA',
             'QUECHOLAC',
             'QUIMIXTLAN',
             'RAFAEL LARA GRAJALES',
             'SAN ANDRES CHOLULA',
             'SAN ANTONIO CAÑADA',
             'SAN DIEGO LA MESA TOCHIMILTZINGO',
             'SAN FELIPE TEOTLALCINGO',
             'SAN FELIPE TEPATLAN',
             'SAN GABRIEL CHILAC',
             'SAN GREGORIO ATZOMPA',
             'SAN JERONIMO TECUANIPAN',
             'SAN JERONIMO XAYACATLAN',
             'SAN JOSE CHIAPA',
             'SAN JOSE MIAHUATLAN',
             'SAN JUAN ATENCO',
             'SAN JUAN ATZOMPA',
             'SAN MARTIN TEXMELUCAN',
             'SAN MARTIN TOTOLTEPEC',
             'SAN MATIAS TLALANCALECA',
             'SAN MIGUEL IXITLAN',
             'SAN MIGUEL XOXTLA',
             'SAN NICOLAS BUENOS AIRES',
             'SAN NICOLAS DE LOS RANCHOS',
             'SAN PABLO ANICANO',
             'SAN PEDRO CHOLULA',
             'SAN PEDRO YELOIXTLAHUACA',
             'SAN SALVADOR EL SECO',
             'SAN SALVADOR EL VERDE',
             'SAN SALVADOR HUIXCOLOTLA',
             'SAN SEBASTIAN TLACOTEPEC',
             'SANTA CATARINA TLALTEMPAN',
             'SANTA INES AHUATEMPAN',
             'SANTA ISABEL CHOLULA',
             'SANTIAGO MIAHUATLAN',
             'SANTO TOMAS HUEYOTLIPAN',
             'SOLTEPEC',
             'TECALI DE HERRERA',
             'TECAMACHALCO',
             'TECOMATLAN',
             'TEHUACAN',
             'TEHUITZINGO',
             'TENAMPULCO',
             'TEOPANTLAN',
             'TEOTLALCO',
             'TEPANCO DE LOPEZ',
             'TEPANGO DE RODRIGUEZ',
             'TEPATLAXCO DE HIDALGO',
             'TEPEACA',
             'TEPEMAXALCO',
             'TEPEOJUMA',
             'TEPETZINTLA',
             'TEPEXCO',
             'TEPEXI DE RODRIGUEZ',
             'TEPEYAHUALCO',
             'TEPEYAHUALCO DE CUAUHTEMOC',
             'TETELA DE OCAMPO',
             'TETELES DE AVILA CASTILLO',
             'TEZIUTLAN',
             'TIANGUISMANALCO',
             'TILAPA',
             'TLACHICHUCA',
             'TLACOTEPEC DE BENITO JUAREZ',
             'TLACUILOTEPEC',
             'TLAHUAPAN',
             'TLALTENANGO',
             'TLANEPANTLA',
             'TLAOLA',
             'TLAPACOYA',
             'TLAPANALA',
             'TLATLAUQUITEPEC',
             'TLAXCO',
             'TOCHIMILCO',
             'TOCHTEPEC',
             'TOTOLTEPEC DE GUERRERO',
             'TULCINGO',
             'TUZAMAPAN DE GALEANA',
             'TZICATLACOYAN',
             'XAYACATLAN DE BRAVO',
             'XICOTEPEC',
             'XICOTLAN',
             'XIUTETELCO',
             'XOCHIAPULCO',
             'XOCHILTEPEC',
             'XOCHITLAN DE VICENTE SUAREZ',
             'XOCHITLAN TODOS SANTOS',
             'YAONAHUAC',
             'YEHUALTEPEC',
             'ZACAPALA',
             'ZACAPOAXTLA',
             'ZACATLAN',
             'ZAPOTITLAN',
             'ZAPOTITLAN DE MENDEZ',
             'ZAUTLA',
             'ZIHUATEUTLA',
             'ZINACATEPEC',
             'ZONGOZOTLA',
             'ZOQUIAPAN',
             'ZOQUITLAN'
         ],
         'QUERETARO' => [
             'AMEALCO DE BONFIL',
             'ARROYO SECO',
             'CADEREYTA DE MONTES',
             'COLON',
             'CORREGIDORA',
             'EL MARQUES',
             'EZEQUIEL MONTES',
             'HUIMILPAN',
             'JALPAN DE SERRA',
             'LANDA DE MATAMOROS',
             'PEDRO ESCOBEDO',
             'PEÑAMILLER',
             'PINAL DE AMOLES',
             'QUERETARO',
             'SAN JOAQUIN',
             'TEQUISQUIAPAN'
         ],
         'QUINTANA ROO' => [
             'BACALAR',
             'COZUMEL',
             'FELIPE CARRILLO PUERTO',
             'ISLA MUJERES',
             'JOSE MARIA MORELOS',
             'OTHON P. BLANCO',
             'SOLIDARIDAD',
             'TULUM'
         ],
         'SAN LUIS POTOSI' => [
             'AHUALULCO',
             'ALAQUINES',
             'AQUISMON',
             'ARMADILLO DE LOS INFANTE',
             'AXTLA DE TERRAZAS',
             'CARDENAS',
             'CATORCE',
             'CEDRAL',
             'CERRITOS',
             'CERRO DE SAN PEDRO',
             'CHARCAS',
             'CIUDAD DEL MAIZ',
             'CIUDAD FERNANDEZ',
             'CIUDAD VALLES',
             'EBANO',
             'EL NARANJO',
             'GUADALCAZAR',
             'HUEHUETLAN',
             'MATEHUALA',
             'MATLAPA',
             'MEXQUITIC DE CARMONA',
             'MOCTEZUMA',
             'RIOVERDE',
             'SALINAS',
             'SAN ANTONIO',
             'SAN CIRO DE ACOSTA',
             'SAN LUIS POTOSI',
             'SAN MARTIN CHALCHICUAUTLA',
             'SAN NICOLAS TOLENTINO',
             'SAN VICENTE TANCUAYALAB',
             'SANTA MARIA DEL RIO',
             'SANTO DOMINGO',
             'SOLEDAD DE GRACIANO SANCHEZ',
             'TAMASOPO',
             'TAMAZUNCHALE',
             'TAMPACAN',
             'TAMPAMOLON CORONA',
             'TAMUIN',
             'TANCANHUITZ',
             'TANLAJAS',
             'TANQUIAN DE ESCOBEDO',
             'TIERRA NUEVA',
             'VANEGAS',
             'VENADO',
             'VILLA DE ARISTA',
             'VILLA DE ARRIAGA',
             'VILLA DE GUADALUPE',
             'VILLA DE LA PAZ',
             'VILLA DE RAMOS',
             'VILLA DE REYES',
             'VILLA JUAREZ',
             'XILITLA'
         ],
         'SINALOA' => [
             'AHOME',
             'ANGOSTURA',
             'BADIRAGUATO',
             'CHOIX',
             'CONCORDIA',
             'COSALA',
             'CULIACAN',
             'EL FUERTE',
             'ELOTA',
             'ESCUINAPA',
             'GUASAVE',
             'MAZATLAN',
             'MOCORITO',
             'NAVOLATO',
             'SALVADOR ALVARADO',
             'SAN IGNACIO',
             'SINALOA'
         ],
         'SONORA' => [
             'ACONCHI',
             'AGUA PRIETA',
             'ALAMOS',
             'ALTAR',
             'ARIVECHI',
             'ARIZPE',
             'ATIL',
             'BACADEHUACHI',
             'BACANORA',
             'BACERAC',
             'BACOACHI',
             'BACUM',
             'BANAMICHI',
             'BAVIACORA',
             'BAVISPE',
             'BENJAMIN HILL',
             'CABORCA',
             'CAJEME',
             'CANANEA',
             'CARBO',
             'CUCURPE',
             'CUMPAS',
             'DIVISADEROS',
             'EMPALME',
             'ETCHOJOA',
             'FRONTERAS',
             'GENERAL PLUTARCO ELIAS CALLES',
             'GRANADOS',
             'GUAYMAS',
             'HERMOSILLO',
             'HUACHINERA',
             'HUASABAS',
             'HUATABAMPO',
             'HUEPAC',
             'IMURIS',
             'LA COLORADA',
             'NACO',
             'NACORI CHICO',
             'NACOZARI DE GARCIA',
             'NAVOJOA',
             'NOGALES',
             'ONAVAS',
             'OPODEPE',
             'OQUITOA',
             'PITIQUITO',
             'PUERTO PEÑASCO',
             'QUIRIEGO',
             'SAHUARIPA',
             'SAN FELIPE DE JESUS',
             'SAN IGNACIO RIO MUERTO',
             'SAN JAVIER',
             'SAN LUIS RIO COLORADO',
             'SAN MIGUEL DE HORCASITAS',
             'SAN PEDRO DE LA CUEVA',
             'SANTA CRUZ',
             'SARIC',
             'SOYOPA',
             'SUAQUI GRANDE',
             'TEPACHE',
             'TRINCHERAS',
             'TUBUTAMA',
             'URES',
             'VILLA PESQUEIRA',
             'YECORA'
         ],
         'TABASCO' => [
             'BALANCAN',
             'CENTLA',
             'CENTRO',
             'COMALCALCO',
             'CUNDUACAN',
             'HUIMANGUILLO',
             'JALAPA',
             'JALPA DE MENDEZ',
             'JONUTA',
             'MACUSPANA',
             'NACAJUCA',
             'PARAISO',
             'TACOTALPA',
             'TEAPA',
             'TENOSIQUE'
         ],
         'TAMAULIPAS' => [
             'ALTAMIRA',
             'ANTIGUO MORELOS',
             'BURGOS',
             'CASAS',
             'CIUDAD MADERO',
             'CRUILLAS',
             'EL MANTE',
             'GONZALEZ',
             'GÜEMEZ',
             'GUSTAVO DIAZ ORDAZ',
             'JAUMAVE',
             'LLERA',
             'MAINERO',
             'MENDEZ',
             'MIER',
             'MIGUEL ALEMAN',
             'MIQUIHUANA',
             'NUEVO LAREDO',
             'NUEVO MORELOS',
             'PADILLA',
             'PALMILLAS',
             'REYNOSA',
             'RIO BRAVO',
             'SAN CARLOS',
             'SOTO LA MARINA',
             'TAMPICO',
             'TULA',
             'VALLE HERMOSO',
             'XICOTENCATL'
         ],
         'TLAXCALA' => [
             'ACUAMANALA DE MIGUEL HIDALGO',
             'ALTZAYANCA',
             'AMAXAC DE GUERRERO',
             'APETATITLAN DE ANTONIO CARVAJAL',
             'APIZACO',
             'ATLANGATEPEC',
             'CALPULALPAN',
             'CHIAUTEMPAN',
             'CONTLA DE JUAN CUAMATZI',
             'CUAPIAXTLA',
             'CUAXOMULCO',
             'EL CARMEN TEQUEXQUITLA',
             'ESPAÑITA',
             'HUAMANTLA',
             'HUEYOTLIPAN',
             'IXTACUIXTLA DE MARIANO MATAMOROS',
             'IXTENCO',
             'LA MAGDALENA TLALTELULCO',
             'MAZATECOCHCO DE JOSE MARIA MORELOS',
             'MUÑOZ DE DOMINGO ARENAS',
             'NANACAMILPA DE MARIANO ARISTA',
             'NATIVITAS',
             'PANOTLA',
             'PAPALOTLA DE XICOHTENCATL',
             'SAN DAMIAN TEXOLOC',
             'SAN FRANCISCO TETLANOHCAN',
             'SAN JERONIMO ZACUALPAN',
             'SAN JOSE TEACALCO',
             'SAN JUAN HUACTZINCO',
             'SAN LORENZO AXOCOMANITLA',
             'SAN LUCAS TECOPILCO',
             'SAN PABLO DEL MONTE',
             'SANCTORUM DE LAZARO CARDENAS',
             'SANTA ANA NOPALUCAN',
             'SANTA APOLONIA TEACALCO',
             'SANTA CATARINA AYOMETLA',
             'SANTA CRUZ QUILEHTLA',
             'SANTA CRUZ TLAXCALA',
             'SANTA ISABEL XILOXOXTLA',
             'TEOLOCHOLCO',
             'TEPETITLA DE LARDIZABAL',
             'TEPEYANCO',
             'TERRENATE',
             'TETLA DE LA SOLIDARIDAD',
             'TETLATLAHUCA',
             'TLAXCALA',
             'TOCATLAN',
             'TOTOLAC',
             'TZOMPANTEPEC',
             'XALOZTOC',
             'XALTOCAN',
             'XICOHTZINCO',
             'YAUHQUEMECAN',
             'ZACATELCO',
             'ZITLALTEPEC DE TRINIDAD SANCHEZ SANTOS'
         ],
         'VERACRUZ' => [
             'ACAYUCAN',
             'ACULA',
             'ACULTZINGO',
             'AGUA DULCE',
             'ALAMO TEMAPACHE',
             'ALPATLAHUAC',
             'ALTO LUCERO DE GUTIERREZ BARRIOS',
             'ALTOTONGA',
             'ALVARADO',
             'AMATITLAN',
             'AMATLAN DE LOS REYES',
             'ANGEL R. CABADA',
             'APAZAPAN',
             'ASTACINGA',
             'ATLAHUILCO',
             'ATZACAN',
             'ATZALAN',
             'AYAHUALULCO',
             'BANDERILLA',
             'BOCA DEL RIO',
             'CALCAHUALCO',
             'CAMARON DE TEJEDA',
             'CAMERINO Z. MENDOZA',
             'CARLOS A. CARRILLO',
             'CARRILLO PUERTO',
             'CASTILLO DE TEAYO',
             'CATEMACO',
             'CAZONES DE HERRERA',
             'CERRO AZUL',
             'CHACALTIANGUIS',
             'CHALMA',
             'CHICONAMEL',
             'CHICONQUIACO',
             'CHICONTEPEC',
             'CHINAMECA',
             'CHINAMPA DE GOROSTIZA',
             'CHOCAMAN',
             'CHONTLA',
             'CHUMATLAN',
             'CITLALTEPETL',
             'COACOATZINTLA',
             'COAHUITLAN',
             'COATZACOALCOS',
             'COATZINTLA',
             'COETZALA',
             'COLIPA',
             'COMAPA',
             'CORDOBA',
             'COSAMALOAPAN',
             'COSAUTLAN DE CARVAJAL',
             'COSCOMATEPEC',
             'COSOLEACAQUE',
             'COTAXTLA',
             'COXQUIHUI',
             'COYUTLA',
             'CUICHAPA',
             'CUITLAHUAC',
             'EL HIGO',
             'ESPINAL',
             'FILOMENO MATA',
             'FORTIN',
             'GUTIERREZ ZAMORA',
             'HIDALGOTITLAN',
             'HUATUSCO',
             'HUAYACOCOTLA',
             'HUEYAPAN DE OCAMPO',
             'HUILOAPAN DE CUAUHTEMOC',
             'IGNACIO DE LA LLAVE',
             'ILAMATLAN',
             'ISLA',
             'IXCATEPEC',
             'IXHUACAN DE LOS REYES',
             'IXHUATLAN DE MADERO',
             'IXHUATLAN DEL CAFE',
             'IXHUATLAN DEL SURESTE',
             'IXHUATLANCILLO',
             'IXMATLAHUACAN',
             'IXTACZOQUITLAN',
             'JALACINGO',
             'JALCOMULCO',
             'JALTIPAN',
             'JAMAPA',
             'JESUS CARRANZA',
             'JOSE AZUETA',
             'JUAN RODRIGUEZ CLARA',
             'JUCHIQUE DE FERRER',
             'LA ANTIGUA',
             'LA PERLA',
             'LANDERO Y COSS',
             'LAS CHOAPAS',
             'LAS MINAS',
             'LAS VIGAS DE RAMIREZ',
             'LERDO DE TEJADA',
             'MALTRATA',
             'MANLIO FABIO ALTAMIRANO',
             'MARIANO ESCOBEDO',
             'MARTINEZ DE LA TORRE',
             'MECATLAN',
             'MECAYAPAN',
             'MEDELLIN',
             'MIAHUATLAN',
             'MISANTLA',
             'MIXTLA DE ALTAMIRANO',
             'MOLOACAN',
             'NANCHITAL DE LAZARO CARDENAS DEL RIO',
             'NAOLINCO',
             'NARANJAL',
             'NARANJOS AMATLAN',
             'NAUTLA',
             'OLUTA',
             'OMEALCA',
             'ORIZABA',
             'OTATITLAN',
             'OTEAPAN',
             'OZULUAMA',
             'PAJAPAN',
             'PANUCO',
             'PAPANTLA',
             'PASO DE OVEJAS',
             'PASO DEL MACHO',
             'PEROTE',
             'PLATON SANCHEZ',
             'PLAYA VICENTE',
             'POZA RICA DE HIDALGO',
             'PUEBLO VIEJO',
             'PUENTE NACIONAL',
             'RAFAEL DELGADO',
             'RAFAEL LUCIO',
             'RIO BLANCO',
             'SALTABARRANCA',
             'SAN ANDRES TENEJAPAN',
             'SAN ANDRES TUXTLA',
             'SAN JUAN EVANGELISTA',
             'SAN RAFAEL',
             'SANTIAGO SOCHIAPAN',
             'SANTIAGO TUXTLA',
             'SAYULA DE ALEMAN',
             'SOCHIAPA',
             'SOCONUSCO',
             'SOLEDAD ATZOMPA',
             'SOLEDAD DE DOBLADO',
             'SOTEAPAN',
             'TAMALIN',
             'TAMIAHUA',
             'TAMPICO ALTO',
             'TANCOCO',
             'TANTIMA',
             'TANTOYUCA',
             'TATAHUICAPAN DE JUAREZ',
             'TATATILA',
             'TECOLUTLA',
             'TEHUIPANGO',
             'TEMPOAL',
             'TENAMPA',
             'TENOCHTITLAN',
             'TEOCELO',
             'TEPATLAXCO',
             'TEPETLAN',
             'TEXCATEPEC',
             'TEXHUACAN',
             'TEXISTEPEC',
             'TEZONAPA',
             'TIHUATLAN',
             'TLACHICHILCO',
             'TLACOJALPAN',
             'TLACOLULAN',
             'TLACOTALPAN',
             'TLACOTEPEC DE MEJIA',
             'TLALIXCOYAN',
             'TLALNELHUAYOCAN',
             'TLALTETELA',
             'TLAPACOYAN',
             'TLAQUILPA',
             'TLILAPAN',
             'TONAYAN',
             'TOTUTLA',
             'TRES VALLES',
             'TUXTILLA',
             'URSULO GALVAN',
             'UXPANAPA',
             'VEGA DE ALATORRE',
             'VERACRUZ',
             'VILLA ALDAMA',
             'XALAPA',
             'XICO',
             'XOXOCOTLA',
             'YANGA',
             'YECUATLA',
             'ZENTLA',
             'ZONGOLICA',
             'ZONTECOMATLAN',
             'ZOZOCOLCO DE HIDALGO'
         ],
         'YUCATAN' => [
             'ABALA',
             'ACANCEH',
             'AKIL',
             'BACA',
             'BOKOBA',
             'BUCTZOTZ',
             'CACALCHEN',
             'CALOTMUL',
             'CANSAHCAB',
             'CANTAMAYEC',
             'CELESTUN',
             'CENOTILLO',
             'CHACSINKIN',
             'CHANKOM',
             'CHAPAB',
             'CHEMAX',
             'CHICHIMILA',
             'CHICXULUB PUEBLO',
             'CHIKINDZONOT',
             'CHOCHOLA',
             'CHUMAYEL',
             'CONKAL',
             'CUNCUNUL',
             'CUZAMA',
             'DZAN',
             'DZEMUL',
             'DZIDZANTUN',
             'DZILAM DE BRAVO',
             'DZILAM GONZALEZ',
             'DZITAS',
             'DZONCAUICH',
             'ESPITA',
             'HALACHO',
             'HOCABA',
             'HOCTUN',
             'HOMUN',
             'HUHI',
             'HUNUCMA',
             'IXIL',
             'IZAMAL',
             'KANASIN',
             'KANTUNIL',
             'KAUA',
             'KINCHIL',
             'KOPOMA',
             'MAMA',
             'MANI',
             'MAXCANU',
             'MAYAPAN',
             'MERIDA',
             'MOCOCHA',
             'MOTUL',
             'MUNA',
             'MUXUPIP',
             'OPICHEN',
             'OXKUTZCAB',
             'PANABA',
             'PETO',
             'QUINTANA ROO',
             'RIO LAGARTOS',
             'SACALUM',
             'SAMAHIL',
             'SANAHCAT',
             'SANTA ELENA',
             'SEYE',
             'SINANCHE',
             'SOTUTA',
             'SUCILA',
             'SUDZAL',
             'SUMA',
             'TAHDZIU',
             'TAHMEK',
             'TEABO',
             'TECOH',
             'TEKAL DE VENEGAS',
             'TEKANTO',
             'TEKAX',
             'TEKIT',
             'TEKOM',
             'TELCHAC PUEBLO',
             'TELCHAC PUERTO',
             'TEMAX',
             'TEMOZON',
             'TEPAKAN',
             'TETIZ',
             'TEYA',
             'TICUL',
             'TIMUCUY',
             'TINUM',
             'TIXCACALCUPUL',
             'TIXKOKOB',
             'TIXMEHUAC',
             'TIXPEHUAL',
             'TIZIMIN',
             'TUNKAS',
             'TZUCACAB',
             'UAYMA',
             'UCU',
             'UMAN',
             'VALLADOLID',
             'XOCCHEL',
             'YAXCABA',
             'YAXKUKUL',
             'YOBAIN'
         ],
         'ZACATECAS' => [
             'APOZOL',
             'APULCO',
             'ATOLINGA',
             'CALERA',
             'CAÑITAS DE FELIPE PESCADOR',
             'CHALCHIHUITES',
             'CONCEPCION DEL ORO',
             'EL PLATEADO DE JOAQUIN AMARO',
             'EL SALVADOR',
             'FRESNILLO',
             'GENARO CODINA',
             'GENERAL ENRIQUE ESTRADA',
             'GENERAL FRANCISCO R. MURGUIA',
             'GENERAL PANFILO NATERA',
             'HUANUSCO',
             'JALPA',
             'JEREZ',
             'JIMENEZ DEL TEUL',
             'JUAN ALDAMA',
             'JUCHIPILA',
             'LUIS MOYA',
             'MAZAPIL',
             'MEZQUITAL DEL ORO',
             'MIGUEL AUZA',
             'MOMAX',
             'MONTE ESCOBEDO',
             'MOYAHUA DE ESTRADA',
             'NOCHISTLAN DE MEJIA',
             'NORIA DE ANGELES',
             'OJOCALIENTE',
             'PINOS',
             'RIO GRANDE',
             'SAIN ALTO',
             'SANTA MARIA DE LA PAZ',
             'SOMBRERETE',
             'SUSTICACAN',
             'TABASCO',
             'TEPECHITLAN',
             'TEPETONGO',
             'TEUL DE GONZALEZ ORTEGA',
             'TLALTENANGO DE SANCHEZ ROMAN',
             'TRANCOSO',
             'TRINIDAD GARCIA DE LA CADENA',
             'VALPARAISO',
             'VETAGRANDE',
             'VILLA DE COS',
             'VILLA GARCIA',
             'VILLA GONZALEZ ORTEGA',
             'VILLANUEVA',
             'ZACATECAS'
         ]
     ];




    /**
     * Funcion que parsea elementos reportados en arreglos para devolverlos en json
     * @param $elementos Conjunto de reportes
     * @param $categoria Categoria a la que pertenecen
     * @return array Elementos parseados
     */
    protected function parseaElementosFoto($elementos, $categoria, $completo=false)
    {
        $resultado = array();
        if(count($elementos)>0){
            foreach($elementos as $index=>$elemento)
            {
                if($completo)
                {
                    $fotos = array();
                    if( isset($elemento['evidencia']) && count($elemento['evidencia'])>0){
                        foreach($elemento['evidencia'] as $foto)
                        {

                            array_push($fotos, Storage::disk('s3')->url($foto));
                        }
                    }
                    array_push($resultado,
                        [
                            'numero'=>$index,
                            'categoria'=>$categoria,
                            'subcategoria'=>$elemento['subcategoria'],
                            'cantidad'=>(array_key_exists('cantidad', $elemento) && isset($elemento['cantidad']))?$elemento['cantidad']:0,
                            'comentario_staff'=>(array_key_exists('comentario_staff', $elemento) && isset($elemento['comentario_staff']))?$elemento['comentario_staff']:"",
                            'atributos'=>(array_key_exists('atributos', $elemento) &&isset($elemento['atributos']))?$elemento['atributos']:array(),
                            'evidencia'=>$fotos,
                            'precio'=>(array_key_exists('precio', $elemento) &&isset($elemento['precio']))?$elemento['precio']:0
                        ]);
                }else{
                    array_push($resultado,
                        [
                            'numero'=>$index,
                            'categoria'=>$categoria,
                            'subcategoria'=>$elemento['subcategoria'],
                            'cantidad'=>(array_key_exists('cantidad', $elemento) && isset($elemento['cantidad']))?$elemento['cantidad']:0,
                            'precio'=>(array_key_exists('precio', $elemento) &&isset($elemento['precio']))?$elemento['precio']:0
                        ]);
                }
            }
        }
        return $resultado;
    }


    /**
     * Funcion para exportar datos a excel
     * @param $data
     * @param string $folder
     * @param bool $s3
     * @return mixed
     */
    protected function exportToExcel( $data, $folder='tierra', $s3 = false)
    {
        $filename = 'Respaldo_'.$folder.'_'.date('YmdHis');
        $file = Excel::create($filename, function($excel) use($data, $folder){
            $excel->setTitle('Respaldo_'.date('Y_m_d_H_i_s'));
            $excel->setDescription('Respaldo del '.date('Y_m_d_H_i_s'));
            if($folder === 'tierra'){
                $excel->sheet('Datos', function($sheet) use($data){
                    $sheet->fromArray($data, null, 'A1', true, true);
                });
            }else{
                foreach($data as $key=>$evento)
                {
                    $excel->sheet("Evento $key", function($sheet)use($evento)
                    {
                        $sheet->cell('A1', function($cell){
                            $cell->setValue('DATOS GENERALES');
                            $cell->setFontSize(16);
                            $cell->setFontWeight('bold');
                        });
                        //Datos Generales
                        $sheet->appendRow(2,array(
                            'alianza',
                            'partido',
                            'fecha',
                            'aforo',
                            'duracion',
                            'compartido',
                            'quienes_aparecen',
                            'sede',
                            'precio_sede',
                            'ubicacion',
                            'direccion',
                            'estado',
                            'estado_id',
                            'circunscripcion',
                            'precio',
                            'usuario_capturo',
                            'revisor',
                            'fecha_revisado',
                            'comentarios',
                            'fecha_enviado_revision',
                            'aprobado_por',
                            'fecha_aprobado',
                            'created_at',
                            'updated_at',
                            'id',
                            'precio_presidente',
                            'precio_senador',
                            'precio_gobernador',
                            'precio_diputadoFederal',
                            'precio_diputadoLocal',
                            'precio_alcalde',
                            'precio_partido'

                        ));
                        $sheet->appendRow($evento['generales']);
                        //Reportes
                        $sheet->cell('A4', function($cell){
                            $cell->setValue('REPORTES DEL EVENTO');
                            $cell->setFontSize(16);
                            $cell->setFontWeight('bold');
                        });
                        $sheet->appendRow(5,array(
                            'categoria',
                            'subcategoria',
                            'cantidad',
                            'precio',
                            'fotos_evidencia',
                            'atributos'
                        ));
                        $sheet->rows($evento['reportes']);
                        //foreach($evento['reportes'] as $reporte)
                        //    $sheet->appendRow($reporte);
                    });
                }
            }
        })->string('xlsx');
        $path = 'respaldos/'.$folder.'/'.$filename;
        $upload = Storage::disk('s3')->put($path, $file);
        if($upload)
            return $path;
        else
            return null;
    }
}
